"""Recover the shared card frame from the stock portraits.

Format 42 keeps a full greyscale portrait in its alpha channel - including the
white torn photo border - while the colour block holds chroma we cannot decode
yet. The border is identical in every stock portrait, so comparing a spread of
them separates it from the art: pixels that barely vary across characters are
frame, pixels that vary are the photo inside it.

Writes frame.npy-ish data as a plain .py module so import_portraits can use it
without re-deriving it every run.

  UMVC3_DIR   folder of stock .tex portraits
  UMVC3_OUT   where to write frame_data.py and a preview
"""
import bpy, sys, os, tempfile

try:
    TOOLS = os.path.dirname(os.path.abspath(__file__))
except NameError:
    TOOLS = os.getcwd()
sys.path.insert(0, TOOLS)
import io_umvc3_mod as M

DIR = os.environ["UMVC3_DIR"]
OUT = os.environ["UMVC3_OUT"]

# A spread of stock characters - enough that art pixels disagree everywhere.
STOCK = ["Ryu", "Wesker", "Leilei", "Phoenix", "Morrigan", "Chris", "Arthur",
         "Frank", "Vergil", "Zero", "Dante", "Tron", "Chunli", "Trish",
         "Felicia", "Spencer", "Gouki", "VJoe", "Haggar", "CViper",
         "Amaterasu", "Nemesis", "RedArremer", "Hiryu", "IronMan", "Thor",
         "Storm", "Wolverine", "SpiderMan", "Hulk"]

lum = []
S = None
for n in STOCK:
    p = os.path.join(DIR, "f_%s00_BM_HQ_NOMIP.tex" % n)
    if not os.path.exists(p):
        continue
    dds = os.path.join(tempfile.gettempdir(), "ft.dds")
    with open(dds, "wb") as f:
        f.write(M.tex_to_dds_bytes(open(p, "rb").read()))
    img = bpy.data.images.load(dds, check_existing=False)
    S = img.size[0]
    px = list(img.pixels)
    bpy.data.images.remove(img)
    # rows come back bottom-up; store top-down
    lum.append([px[((S - 1 - y) * S + x) * 4 + 3] for y in range(S) for x in range(S)])

n = len(lum)
print("using %d stock portraits at %dx%d" % (n, S, S))
if n < 5:
    raise RuntimeError("not enough stock portraits found")

mean = [0.0] * (S * S)
for L in lum:
    for i in range(S * S):
        mean[i] += L[i]
for i in range(S * S):
    mean[i] /= n

var = [0.0] * (S * S)
for L in lum:
    for i in range(S * S):
        d = L[i] - mean[i]
        var[i] += d * d
sd = [(v / n) ** 0.5 for v in var]

THRESH = 0.055
mask = [s < THRESH for s in sd]            # True = frame (shared)

# the art window is the bounding box of the varying pixels
xs = [i % S for i, m in enumerate(mask) if not m]
ys = [i // S for i, m in enumerate(mask) if not m]
X0, X1, Y0, Y1 = min(xs), max(xs) + 1, min(ys), max(ys) + 1
print("art window x %d..%d  y %d..%d  (%dx%d)  frame pixels %d/%d"
      % (X0, X1, Y0, Y1, X1 - X0, Y1 - Y0, sum(1 for m in mask if m), S * S))

with open(os.path.join(OUT, "frame_data.py"), "w") as f:
    f.write("# generated by frame_template.py - shared card frame, %d stock portraits\n" % n)
    f.write("SIZE = %d\n" % S)
    f.write("WINDOW = (%d, %d, %d, %d)\n" % (X0, Y0, X1, Y1))
    f.write("MASK = %r\n" % (bytes(1 if m else 0 for m in mask),))
    f.write("LUM = %r\n" % (bytes(int(min(1.0, max(0.0, v)) * 255 + 0.5) for v in mean),))
print("wrote frame_data.py")

# preview: frame where shared, mid grey where the art goes
buf = [0.0] * (S * S * 4)
for y in range(S):
    for x in range(S):
        i = y * S + x
        v = mean[i] if mask[i] else 0.35
        d = ((S - 1 - y) * S + x) * 4
        buf[d] = buf[d + 1] = buf[d + 2] = v
        buf[d + 3] = 1.0
im = bpy.data.images.new("frame", S, S, alpha=True)
im.pixels = buf
im.filepath_raw = os.path.join(OUT, "frame_preview.png")
im.file_format = "PNG"
im.save()
print("wrote frame_preview.png")
