//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 CBHDRFactor__packed0;
//   float4 CBMaterial__packed0;
//   float4 CBROPTest__packed0;
//   float4 Globals__packed0;
//   sampler2D SSAlbedoMap__tAlbedoMap;
//   float fGlobalTransparency;
//
//
// Registers:
//
//   Name                    Reg   Size
//   ----------------------- ----- ----
//   CBHDRFactor__packed0    c1       1
//   CBROPTest__packed0      c2       1
//   fGlobalTransparency     c3       1
//   CBMaterial__packed0     c4       1
//   Globals__packed0        c5       1
//   SSAlbedoMap__tAlbedoMap s0       1
//

    ps_3_0
    def c0, -1, -0, -0.482353002, 0.344139993
    def c6, 0.714139998, 1.40199995, 1.77199996, 0
    dcl_texcoord v0
    dcl_texcoord1 v1.w
    dcl_texcoord2 v2.xy
    dcl_2d s0
    texld r0, v2, s0
    mul r0.y, r0.y, v0.w
    mul r1.x, r0.y, c4.w
    mov r1.w, c4.w
    mad r0.y, r0.y, -r1.w, c2.x
    cmp r2, r0.y, c0.x, c0.y
    texkill r2
    add r2, r0.xzxz, c0.z
    mad r0.x, r2.y, -c0.w, r0.w
    mad r0.y, r2.z, -c6.x, r0.x
    mad r0.xz, r2.xyww, c6.yyzw, r0.w
    mul r0.xyz, r0, c5.yzww
    add r1.yzw, c4.xxyz, v0.xxyz
    mul r1.yzw, r1, v1.w
    mul r0.xyz, r0, r1.yzww
    mul oC0.w, r1.x, c3.x
    mul oC0.xyz, r0, c1.x

// approximately 17 instruction slots used (1 texture, 16 arithmetic)
